version: '2'

services: 
  api:
    image: tianon/true
    volumes:
      - ./quickstart:/var/www/html
  api-php-fpm:
    image: php:7.1-fpm-alpine
    volumes_from:
      - api
    links: 
      - api-db
      - test-api-db
      - api-redis
      - test-api-redis
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-virtualhost.conf:/etc/nginx/sites-availalbe/virtualhost.conf
    # volume_from:
    #   - api
    ports:
      - '80:80'
      - '443:443'
    links:
      - api-php-fpm
  api-db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database1
    volumes:
      - api-db:/var/lib/mysql
    command: []
  
  test-api-db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database1
    volumes:
      - test-api-db:/var/lib/mysql
    command: []
  
  api-redis:
    image: redis:alpine
    ports: 
      - '6379:6379'
  
  test-api-redis:
    image: redis:alpine
    ports: 
      - '6380:6380'

volumes:
  api-db:
    external: true
  test-api-db:
    external: true
  api-redis:
  test-api-redis: